name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # atau versi Node.js yang sesuai

      - name: Install dependencies
        run: |
          npm ci  # atau npm install jika Anda belum menggunakan package-lock.json

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
