name: Run Playwright Tests

on:
  push:
    branches:
      - main # Atau branch yang kamu inginkan
  pull_request:
    branches:
      - main # Atau branch yang kamu inginkan

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: Playwright  # <- sesuaikan jika project kamu ada di dalam folder ini

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: Playwright  # <- sesuaikan juga

